<?php

use Illuminate\Database\Seeder;

class AccountSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('tbl_accounts')->insert(['account_number' => '1', 'account_name' => ' الموجودات', 'master_account_number' =>' ', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '11', 'account_name' => ' الأصول طويلة الأجل', 'master_account_number' =>'1', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '111', 'account_name' => ' الأراضي', 'master_account_number' =>'11', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '1111', 'account_name' => ' أراضي بناء', 'master_account_number' =>'111', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '1112', 'account_name' => ' أراضي فضاء', 'master_account_number' =>'111', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '1113', 'account_name' => ' أراضي حدائق', 'master_account_number' =>'111', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '112', 'account_name' => ' مباني ومرافق', 'master_account_number' =>'11', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '11201', 'account_name' => ' إكساء وتهيئة المقر المؤقت', 'master_account_number' =>'112', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '113', 'account_name' => ' وسائل نقل وانتقال', 'master_account_number' =>'11', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '1131', 'account_name' => ' سيارات / ميكرو باصات', 'master_account_number' =>'113', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '1132', 'account_name' => ' سيارات / باصات', 'master_account_number' =>'113', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '1133', 'account_name' => ' سيارات سياحية', 'master_account_number' =>'113', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '1134', 'account_name' => ' وسائل نقل وانتقال أخرى', 'master_account_number' =>'113', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '114', 'account_name' => ' عدد وأدوات وآلات حاسبة', 'master_account_number' =>'11', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '115', 'account_name' => ' أثاث ومعدات مكاتب وأجهزة حاسوبية', 'master_account_number' =>'11', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '1151', 'account_name' => ' أثاث', 'master_account_number' =>'115', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '1152', 'account_name' => ' أجهزة حاسوبية ومتتماتها', 'master_account_number' =>'115', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '1153', 'account_name' => ' أجهزة تكييف وتبريد', 'master_account_number' =>'115', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '1154', 'account_name' => ' أثاث وأدوات مكاتب أخرى', 'master_account_number' =>'115', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '116', 'account_name' => ' الأصول غير الملموسة', 'master_account_number' =>'11', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '1161', 'account_name' => ' نفقات تأسيس', 'master_account_number' =>'116', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '1162', 'account_name' => ' برامج محاسبية وذاتية', 'master_account_number' =>'116', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '12', 'account_name' => ' مشروعات تحت التنفيذ', 'master_account_number' =>'1', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '121', 'account_name' => ' تكوين استثماري', 'master_account_number' =>'12', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '122', 'account_name' => ' انفاق استثماري', 'master_account_number' =>'12', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '123', 'account_name' => ' اعتمادات مستندية وسلف طويلة الأجل', 'master_account_number' =>'12', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '13', 'account_name' => ' استثمارات طويلة الأجل', 'master_account_number' =>'1', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '131', 'account_name' => ' استثمارات عقارية', 'master_account_number' =>'13', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '132', 'account_name' => ' إقراض طويل الأجل', 'master_account_number' =>'13', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '14', 'account_name' => ' المخزون ', 'master_account_number' =>'1', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '141', 'account_name' => ' مخزون اللوازم', 'master_account_number' =>'14', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '142', 'account_name' => ' مخزون الوقود والزيوت', 'master_account_number' =>'14', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '143', 'account_name' => ' مخزون المواد الأخرى', 'master_account_number' =>'14', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '15', 'account_name' => ' مدينون', 'master_account_number' =>'1', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '151', 'account_name' => ' المنتسبون', 'master_account_number' =>'15', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '15101', 'account_name' => ' المنتسبون في محافظة دمشق', 'master_account_number' =>'151', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '15102', 'account_name' => ' المنتسبون في محافظة ريف دمشق', 'master_account_number' =>'151', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '15103', 'account_name' => ' المنتسبون في محافظة اللاذقية', 'master_account_number' =>'151', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '15104', 'account_name' => ' المنتسبون في محافظة طرطوس', 'master_account_number' =>'151', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '15105', 'account_name' => ' المنتسبون في محافظة حلب', 'master_account_number' =>'151', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '15106', 'account_name' => ' المنتسبون في محافظة حمص', 'master_account_number' =>'151', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '15107', 'account_name' => ' المنتسبون في محافظة حماه', 'master_account_number' =>'151', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '15108', 'account_name' => ' المنتسبون في محافظة السويداء', 'master_account_number' =>'151', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '15109', 'account_name' => ' المنتسبون في محافظة القنيطرة', 'master_account_number' =>'151', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '15110', 'account_name' => ' المنتسبون في محافظة درعا', 'master_account_number' =>'151', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '152', 'account_name' => ' أوراق قبض', 'master_account_number' =>'15', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '153', 'account_name' => ' حساب الأعضاء غير المستكملين - معلق', 'master_account_number' =>'15', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '16', 'account_name' => ' حسابات مدينة مختلفة', 'master_account_number' =>'1', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '161', 'account_name' => ' مصروفات مدفوعة مسبقاً', 'master_account_number' =>'16', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '16101', 'account_name' => ' مصاريف ايجارات مدفوعة مسبقا', 'master_account_number' =>'161', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '16102', 'account_name' => ' مصاريف مختلفة مدفوعة مقدماً', 'master_account_number' =>'161', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '162', 'account_name' => ' ايرادات جارية مستحقة غير مقبوضة', 'master_account_number' =>'16', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '163', 'account_name' => ' أرصدة مدينة أخرى', 'master_account_number' =>'16', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '164', 'account_name' => ' العجز', 'master_account_number' =>'16', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '1641', 'account_name' => ' عجز الدورة', 'master_account_number' =>'164', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '1642', 'account_name' => ' العجز المتراكم', 'master_account_number' =>'164', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '17', 'account_name' => ' النقدية ومعادل النقدية', 'master_account_number' =>'1', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '171', 'account_name' => ' الصندوق', 'master_account_number' =>'17', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '172', 'account_name' => ' المصرف - حساب جاري', 'master_account_number' =>'17', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '17201', 'account_name' => ' المصرف العقاري', 'master_account_number' =>'172', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '1720101', 'account_name' => ' المصرف العقاري - دمشق - فرع التعاوني حـ 11011418', 'master_account_number' =>'17201', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '17202', 'account_name' => ' مصرف فرنسبنك', 'master_account_number' =>'172', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '1720201', 'account_name' => ' مصرف فرنسبنك _ فرع دمشق', 'master_account_number' =>'17202', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '1720202', 'account_name' => ' مصرف فرنسبنك _ فرع حلب', 'master_account_number' =>'17202', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '1720203', 'account_name' => ' مصرف فرنسبنك _ فرع طرطوس', 'master_account_number' =>'17202', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '1720204', 'account_name' => ' مصرف فرنسبنك _ فرع اللاذقية', 'master_account_number' =>'17202', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '17203', 'account_name' => ' مصرف بيمو', 'master_account_number' =>'172', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '1720301', 'account_name' => ' مصرف بيمو _ فرع حمص', 'master_account_number' =>'17203', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '173', 'account_name' => ' المصرف - ودائع لأجل', 'master_account_number' =>'17', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '174', 'account_name' => ' السلف', 'master_account_number' =>'17', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '1741', 'account_name' => ' سلف عاملين', 'master_account_number' =>'174', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '174101', 'account_name' => ' السائق محمد حسام المرعي', 'master_account_number' =>'1741', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '174102', 'account_name' => ' ولاء الجبان', 'master_account_number' =>'1741', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '174103', 'account_name' => ' عليا العلي', 'master_account_number' =>'1741', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '174104', 'account_name' => ' نعمت قياس', 'master_account_number' =>'1741', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '174105', 'account_name' => ' دانه حبال', 'master_account_number' =>'1741', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '174106', 'account_name' => ' العامل عمار أفه دار', 'master_account_number' =>'1741', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '1742', 'account_name' => ' سلف مهمات الانتقال والسفر', 'master_account_number' =>'174', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '1743', 'account_name' => ' سلف لأغراض النشاط', 'master_account_number' =>'174', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '1744', 'account_name' => ' سلف لأغراض البحث العلمي', 'master_account_number' =>'174', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '1745', 'account_name' => ' سلف لتسيير أعمال النقابة', 'master_account_number' =>'174', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '1746', 'account_name' => ' سلف للمتعهدين', 'master_account_number' =>'174', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '1747', 'account_name' => ' العاملة اسراء فليون', 'master_account_number' =>'174', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '2', 'account_name' => ' المطاليب', 'master_account_number' =>' ', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '21', 'account_name' => ' هدايا وتبرعات عينية', 'master_account_number' =>'2', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '211', 'account_name' => ' رأس المال', 'master_account_number' =>'21', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '22', 'account_name' => ' مجمع الاهتلاك', 'master_account_number' =>'2', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '221', 'account_name' => ' مجمع اهتلاك مصاريف اكساء المقر المؤقت', 'master_account_number' =>'22', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '222', 'account_name' => ' مجمع اهتلاك مباني', 'master_account_number' =>'22', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '223', 'account_name' => ' مجمع اهتلاك وسائل نقل وانتقال', 'master_account_number' =>'22', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '224', 'account_name' => ' مجمع اهتلاك أثاث ومعدات مكاتب', 'master_account_number' =>'22', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '225', 'account_name' => ' مجمع اهتلاك أصول غير ملموسة', 'master_account_number' =>'22', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '226', 'account_name' => ' مجمع اهتلاك أجهزة حاسوبية ومتتماتها', 'master_account_number' =>'22', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '23', 'account_name' => ' المخصصات', 'master_account_number' =>'2', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '231', 'account_name' => ' مخصص الديون المشكوك فيها', 'master_account_number' =>'23', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '232', 'account_name' => ' مخصص انخفاض قيمة الأصول طويلة الأجل', 'master_account_number' =>'23', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '233', 'account_name' => ' مخصص خصم أوراق قبض', 'master_account_number' =>'23', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '234', 'account_name' => ' مخصصات أخرى', 'master_account_number' =>'23', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '24', 'account_name' => ' التزامات طويلة الأجل', 'master_account_number' =>'2', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '241', 'account_name' => ' سلف وزارة المالية', 'master_account_number' =>'24', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '242', 'account_name' => ' قروض محلية', 'master_account_number' =>'24', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '243', 'account_name' => ' قروض خارجية', 'master_account_number' =>'24', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '244', 'account_name' => ' التزامات أخرى طويلة الأجل', 'master_account_number' =>'24', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '245', 'account_name' => ' نتائج السنوات', 'master_account_number' =>'24', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '2016', 'account_name' => ' نتيجة 2016', 'master_account_number' =>'201', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '25', 'account_name' => ' التزامات قصيرة الأجل', 'master_account_number' =>'2', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '251', 'account_name' => ' الحسابات الدائنة', 'master_account_number' =>'25', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '2511', 'account_name' => ' موردون', 'master_account_number' =>'251', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '251101', 'account_name' => ' جمعية المحاسبين القانونيين', 'master_account_number' =>'2511', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '251102', 'account_name' => ' الاتحاد العام النسائي', 'master_account_number' =>'2511', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '251103', 'account_name' => ' المتعهدون', 'master_account_number' =>'2511', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '251104', 'account_name' => ' عالم الرقميات للتجهيزات الحاسوبية', 'master_account_number' =>'2511', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '251105', 'account_name' => ' مركز التجهيزات الرقمية', 'master_account_number' =>'2511', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '251106', 'account_name' => ' فنادق', 'master_account_number' =>'2511', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '251107', 'account_name' => ' ماهر القلم', 'master_account_number' =>'2511', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '251108', 'account_name' => ' بدر الدين هيثم فيومي', 'master_account_number' =>'2511', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '251109', 'account_name' => ' عالم الطابعات والاحبار', 'master_account_number' =>'2511', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '251110', 'account_name' => ' عماد فهد الشحادة', 'master_account_number' =>'2511', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '251111', 'account_name' => ' بيست اكش ( حازم حيدر', 'master_account_number' =>'2511', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '251112', 'account_name' => ' الشركة الاسلامية للتأمين', 'master_account_number' =>'2511', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '251113', 'account_name' => ' مدقق الحسابات', 'master_account_number' =>'2511', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '251114', 'account_name' => ' القيادة المركزية لحزب البعث العربي الاشتراكي', 'master_account_number' =>'2511', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '2512', 'account_name' => ' أوراق دفع', 'master_account_number' =>'251', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '2513', 'account_name' => ' تأمينات للغير', 'master_account_number' =>'251', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '2514', 'account_name' => ' أقساط القروض وقروض قصيرة الأجل', 'master_account_number' =>'251', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '2515', 'account_name' => ' الدوائر المالية', 'master_account_number' =>'251', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '251501', 'account_name' => ' مديرية مالية دمشق - ضريبة الرواتب والأجور', 'master_account_number' =>'2515', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '251502', 'account_name' => ' مديرية مالية دمشق - ضريبة القانون /60/', 'master_account_number' =>'2515', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '251503', 'account_name' => ' مؤسسة التأمينات الاجتماعية', 'master_account_number' =>'2515', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '2517', 'account_name' => ' حسابات دائنة', 'master_account_number' =>'251', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '2518', 'account_name' => ' حسابات جارية', 'master_account_number' =>'251', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '25181', 'account_name' => ' جاري دمشق', 'master_account_number' =>'2518', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '25182', 'account_name' => ' جاري حمص', 'master_account_number' =>'2518', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '25183', 'account_name' => ' جاري حماة', 'master_account_number' =>'2518', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '25184', 'account_name' => ' جاري درعا', 'master_account_number' =>'2518', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '25185', 'account_name' => ' جاري السويداء', 'master_account_number' =>'2518', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '25186', 'account_name' => ' جاري طرطوس', 'master_account_number' =>'2518', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '25187', 'account_name' => ' جاري اللاذقية', 'master_account_number' =>'2518', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '25188', 'account_name' => ' جاري حلب', 'master_account_number' =>'2518', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '25189', 'account_name' => ' جاري القنيطرة', 'master_account_number' =>'2518', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '25190', 'account_name' => ' جاري ريف دمشق', 'master_account_number' =>'2519', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '25191', 'account_name' => ' جاري الأفرع ( معلق ', 'master_account_number' =>'2519', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '25192', 'account_name' => ' جاري الحسكة', 'master_account_number' =>'2519', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '25193', 'account_name' => ' جاري الرقة', 'master_account_number' =>'2519', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '25194', 'account_name' => ' جاري دير الزور', 'master_account_number' =>'2519', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '2519', 'account_name' => ' أمانات للغير', 'master_account_number' =>'251', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '251901', 'account_name' => ' أمانات لشركة التأمين الصحي', 'master_account_number' =>'2519', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '252', 'account_name' => ' حسابات دائنة مختلفة', 'master_account_number' =>'25', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '2521', 'account_name' => ' المصروفات المستحقة وغير المدفوعة', 'master_account_number' =>'252', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '252101', 'account_name' => ' رواتب وتعويضات مستحقة', 'master_account_number' =>'2521', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '252102', 'account_name' => ' فواتير الهاتف المستحقة', 'master_account_number' =>'2521', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '252103', 'account_name' => ' مصاريف ايجارات مستحقة', 'master_account_number' =>'2521', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '252104', 'account_name' => ' مصاريف مستحقة مختلفة', 'master_account_number' =>'2521', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '2522', 'account_name' => ' ايرادات مقبوضة مقدماً', 'master_account_number' =>'252', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '2523', 'account_name' => ' شيكات برسم الدفع', 'master_account_number' =>'252', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '26', 'account_name' => ' الوفر', 'master_account_number' =>'2', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '261', 'account_name' => ' وفر الدورة', 'master_account_number' =>'26', 'report' =>1, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '261001', 'account_name' => ' (عجز دورة عام 2015', 'master_account_number' =>'261', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '261002', 'account_name' => ' وفورات دورة عام 2016', 'master_account_number' =>'261', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '261003', 'account_name' => ' وفورات دورة عام 2017', 'master_account_number' =>'261', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '261004', 'account_name' => ' وفورات دورة عام 2018', 'master_account_number' =>'261', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '262', 'account_name' => ' الوفر المتراكم', 'master_account_number' =>'26', 'report' =>1, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '3', 'account_name' => ' الاستخدامات (النفقات', 'master_account_number' =>' ', 'report' =>2, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '31', 'account_name' => ' رواتب وأجور', 'master_account_number' =>'3', 'report' =>2, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '311', 'account_name' => ' أجور نقدية', 'master_account_number' =>'31', 'report' =>2, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '3111', 'account_name' => ' رواتب وأجور عن أيام العمل الفعلي', 'master_account_number' =>'311', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '3112', 'account_name' => ' متممات الرواتب والأجور النقدية الفعلي', 'master_account_number' =>'311', 'report' =>2, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '31121', 'account_name' => ' تعويض عائلي', 'master_account_number' =>'3112', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '31122', 'account_name' => ' تعويض معيشي', 'master_account_number' =>'3112', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '3113', 'account_name' => ' تعويض العمل الاضافي', 'master_account_number' =>'311', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '3114', 'account_name' => ' تعويض المسؤولية', 'master_account_number' =>'311', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '3115', 'account_name' => ' رواتب وتعويضات أخرى', 'master_account_number' =>'311', 'report' =>2, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '311501', 'account_name' => ' تعويض حضور جلسات مجلس الادارة', 'master_account_number' =>'3115', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '311502', 'account_name' => ' تعويض نقل وانتقال', 'master_account_number' =>'3115', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '311503', 'account_name' => ' تعويضات مهمات السفر للعاملين ومجلس الادارة', 'master_account_number' =>'3115', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '311504', 'account_name' => ' تعويضات مختلفة', 'master_account_number' =>'3115', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '3116', 'account_name' => ' مكافآت تشجيعية أخرى', 'master_account_number' =>'311', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '312', 'account_name' => ' مزايا عينية', 'master_account_number' =>'31', 'report' =>2, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '3121', 'account_name' => ' العلاج', 'master_account_number' =>'312', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '3122', 'account_name' => ' اللباس', 'master_account_number' =>'312', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '3123', 'account_name' => ' خدمات نقل العاملين', 'master_account_number' =>'312', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '313', 'account_name' => ' مصروف التأمينات الاجتماعية حصة رب العمل', 'master_account_number' =>'31', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '314', 'account_name' => ' الأجور لقاء العجز والتقاعد والفرز والتفرغ', 'master_account_number' =>'31', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '32', 'account_name' => ' نفقات مستلزمات الخدمة العامة', 'master_account_number' =>'3', 'report' =>2, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '321', 'account_name' => ' وقود و زيوت', 'master_account_number' =>'32', 'report' =>2, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '3211', 'account_name' => ' بنزين', 'master_account_number' =>'321', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '3212', 'account_name' => ' مازوت', 'master_account_number' =>'321', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '3213', 'account_name' => ' زيوت وشحوم', 'master_account_number' =>'321', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '322', 'account_name' => ' أدوات كتابية وكتب ومطبوعات', 'master_account_number' =>'32', 'report' =>2, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '3221', 'account_name' => ' قرطاسية و مطبوعات', 'master_account_number' =>'322', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '3222', 'account_name' => ' نفقات الاشتراك في الصحف', 'master_account_number' =>'322', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '3223', 'account_name' => ' نفقات طباعة بطاقات عضوية المنتسبين', 'master_account_number' =>'322', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '323', 'account_name' => ' مصاريف الصيانة', 'master_account_number' =>'32', 'report' =>2, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '32301', 'account_name' => ' مصاريف صيانة و لوازم سيارات النقابة', 'master_account_number' =>'323', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '32302', 'account_name' => ' مصاريف صيانة أخرى', 'master_account_number' =>'323', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '32303', 'account_name' => ' مصاريف صيانة أجهزة حاسوبية ومكتبية', 'master_account_number' =>'323', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '324', 'account_name' => ' دعاية واعلان', 'master_account_number' =>'32', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '325', 'account_name' => ' مصاريف نقل وانتقال', 'master_account_number' =>'32', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '326', 'account_name' => ' استئجار آلات ومعدات ووسائل نقل', 'master_account_number' =>'32', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '327', 'account_name' => ' تأهيل و تدريب', 'master_account_number' =>'32', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '328', 'account_name' => ' مصروفات خدمية', 'master_account_number' =>'32', 'report' =>2, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '3281', 'account_name' => ' كهرباء', 'master_account_number' =>'328', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '3282', 'account_name' => ' مياه', 'master_account_number' =>'328', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '3283', 'account_name' => ' بريد', 'master_account_number' =>'328', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '3284', 'account_name' => ' هاتف وانترنت', 'master_account_number' =>'328', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '329', 'account_name' => ' مصروفات خدمية مختلفة', 'master_account_number' =>'32', 'report' =>2, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '3291', 'account_name' => ' مصروفات التأمين', 'master_account_number' =>'329', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '3292', 'account_name' => ' مكافآت لغير العاملين', 'master_account_number' =>'329', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '3293', 'account_name' => ' عمولات مختلفة', 'master_account_number' =>'329', 'report' =>2, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '329301', 'account_name' => ' عمولات مصرفية', 'master_account_number' =>'3293', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '3294', 'account_name' => ' نفقات مدققي الحسابات', 'master_account_number' =>'329', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '3295', 'account_name' => ' علاقات عامة واستقبال', 'master_account_number' =>'329', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '3296', 'account_name' => ' ايجارات فعلية', 'master_account_number' =>'329', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '3297', 'account_name' => ' فوائد', 'master_account_number' =>'329', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '3298', 'account_name' => ' غرامات وتعويضات للغير', 'master_account_number' =>'329', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '3299', 'account_name' => ' أعباء المخصصات', 'master_account_number' =>'329', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '330', 'account_name' => ' مصاريف تجهيزات حاسوبية ومتمماتها', 'master_account_number' =>'33', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '33', 'account_name' => ' نفقات مستلزمات النشاط الخاص', 'master_account_number' =>'3', 'report' =>2, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '331', 'account_name' => ' نفقات اصدار الكتب والمطبوعات', 'master_account_number' =>'33', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '332', 'account_name' => ' اشتراكات في الهيئات المحلية والدولية', 'master_account_number' =>'33', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '333', 'account_name' => ' نفقات النشاط الثقافي والاجتماعي', 'master_account_number' =>'33', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '334', 'account_name' => ' نفقات مختلفة أخرى', 'master_account_number' =>'33', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '335', 'account_name' => ' نفقات موقع النقابة على شبكة الانترنت', 'master_account_number' =>'33', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '34', 'account_name' => ' أعباء الاهتلاك', 'master_account_number' =>'3', 'report' =>2, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '341', 'account_name' => ' اهتلاك إكساء وتهيئة المقر', 'master_account_number' =>'34', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '342', 'account_name' => ' اهتلاك المباني', 'master_account_number' =>'34', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '343', 'account_name' => ' اهتلاك وسائل نقل وانتقال', 'master_account_number' =>'34', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '344', 'account_name' => ' اهتلاك عدد وأدوات وآلات حاسبة', 'master_account_number' =>'34', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '345', 'account_name' => ' اهتلاك أثاث ومعدات مكاتب', 'master_account_number' =>'34', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '346', 'account_name' => ' اهتلاك أصول غير ملموسة', 'master_account_number' =>'34', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '347', 'account_name' => ' اهتلاك أجهزة حاسوبية ومتتماتها', 'master_account_number' =>'34', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '35', 'account_name' => ' ضرائب و رسوم', 'master_account_number' =>'3', 'report' =>2, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '351', 'account_name' => ' ضريبة ريع العقارات', 'master_account_number' =>'35', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '352', 'account_name' => ' رسوم وتأمين السيارات السنوية', 'master_account_number' =>'35', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '353', 'account_name' => ' ضرائب ورسوم أخرى', 'master_account_number' =>'35', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '36', 'account_name' => ' مصاريف متنوعة أخرى', 'master_account_number' =>'3', 'report' =>2, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '361', 'account_name' => ' خسائر رأسمالية', 'master_account_number' =>'36', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '362', 'account_name' => ' ديون معدومة', 'master_account_number' =>'36', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '363', 'account_name' => ' مصروفات سنوات سابقة', 'master_account_number' =>'36', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '364', 'account_name' => ' مصاريف خصم الأوراق التجارية', 'master_account_number' =>'36', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '365', 'account_name' => ' مصروفات متنوعة أخرى', 'master_account_number' =>'36', 'report' =>2, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '36501', 'account_name' => ' لوازم بوفيه وضيافة', 'master_account_number' =>'365', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '36502', 'account_name' => ' لوازم مواد وأجور تنظيف', 'master_account_number' =>'365', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '36503', 'account_name' => ' تجهيزات ولوازم متفرقة', 'master_account_number' =>'365', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '36504', 'account_name' => ' مصاريف أمن وحراسة', 'master_account_number' =>'365', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '36505', 'account_name' => ' مصاريف شحن', 'master_account_number' =>'365', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '36506', 'account_name' => ' فروقات ليرة سورية', 'master_account_number' =>'365', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '366', 'account_name' => ' اقامات فنادق ومطاعم', 'master_account_number' =>'36', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '367', 'account_name' => ' هدايا واكراميات', 'master_account_number' =>'36', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '368', 'account_name' => ' مصاريف قضائية', 'master_account_number' =>'36', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '4', 'account_name' => ' الموارد', 'master_account_number' =>' ', 'report' =>2, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '41', 'account_name' => ' ايرادات النشاط الأساسي', 'master_account_number' =>'4', 'report' =>2, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '411', 'account_name' => ' رسوم الاشتراك السنوية', 'master_account_number' =>'41', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '412', 'account_name' => ' رسوم التسجيل', 'master_account_number' =>'41', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '413', 'account_name' => ' رسوم اعادة التسجيل', 'master_account_number' =>'41', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '414', 'account_name' => ' رسوم انتقال الأعضاء بين الفروع', 'master_account_number' =>'41', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '415', 'account_name' => ' الحصة من أتعاب التحكيم وحل النزاعات والخبرات التي يتقاضاها الأعضاء', 'master_account_number' =>'41', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '416', 'account_name' => ' ايرادات أخرى', 'master_account_number' =>'41', 'report' =>2, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '41601', 'account_name' => ' ايرادات تنظيم و طباعة بطاقات عضوية', 'master_account_number' =>'416', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '41602', 'account_name' => ' ايرادات منح وثائق عضوية', 'master_account_number' =>'416', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '41603', 'account_name' => ' ايرادات طلبات انتساب مرفوضة', 'master_account_number' =>'416', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '41604', 'account_name' => ' ايرادات الموقع الالكتروني', 'master_account_number' =>'416', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '42', 'account_name' => ' ايرادات النشاط غير الأساسي', 'master_account_number' =>'4', 'report' =>2, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '421', 'account_name' => ' اعانات وهبات وهدايا', 'master_account_number' =>'42', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '422', 'account_name' => ' تبرع ومنح و وصايا', 'master_account_number' =>'42', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '423', 'account_name' => ' ريع الحفلات والنشاطات الثقافية والاجتماعية', 'master_account_number' =>'42', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '424', 'account_name' => ' عوائد الاستثمار', 'master_account_number' =>'42', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '425', 'account_name' => ' ايرادات المجلات والمطبوعات والنشرات', 'master_account_number' =>'42', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '426', 'account_name' => ' ايراد التأمين الصحي', 'master_account_number' =>'42', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '43', 'account_name' => ' ايرادات متنوعة', 'master_account_number' =>'4', 'report' =>2, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '431', 'account_name' => ' ايجارات دائنة', 'master_account_number' =>'43', 'report' =>2, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '4311', 'account_name' => ' ايجار مباني', 'master_account_number' =>'431', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '4312', 'account_name' => ' ايجار وسائل نقل', 'master_account_number' =>'431', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '432', 'account_name' => ' خصم نقدي مكتسب', 'master_account_number' =>'43', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '433', 'account_name' => ' حسومات مكتسبة', 'master_account_number' =>'43', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '434', 'account_name' => ' ديون سبق اعدامها', 'master_account_number' =>'43', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '435', 'account_name' => ' تعويضات وغرامات على الغير', 'master_account_number' =>'43', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '436', 'account_name' => ' إعادة مخصصات غير مستعملة', 'master_account_number' =>'43', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '437', 'account_name' => ' عمولات وايرادات متنوعة اخرى', 'master_account_number' =>'43', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '44', 'account_name' => ' ايرادات رأسمالية وتمويلية', 'master_account_number' =>'4', 'report' =>2, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '441', 'account_name' => ' أرباح رأسمالية', 'master_account_number' =>'44', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '442', 'account_name' => ' إيرادات سنوات سابقة', 'master_account_number' =>'44', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '443', 'account_name' => ' فوائد دائنة', 'master_account_number' =>'44', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '6', 'account_name' => ' فارغ', 'master_account_number' =>' ', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '601', 'account_name' => ' فارغ - فرعي', 'master_account_number' =>'60', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '7', 'account_name' => ' البضاعة', 'master_account_number' =>' ', 'report' =>2, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '71', 'account_name' => ' بضاعة اول المدة', 'master_account_number' =>'7', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '72', 'account_name' => ' بضاعة آخر المدة', 'master_account_number' =>'7', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '8', 'account_name' => ' صافي المبيعات', 'master_account_number' =>' ', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '410', 'account_name' => ' المبيعات', 'master_account_number' =>'41', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '420', 'account_name' => ' مرتجع المبيعات', 'master_account_number' =>'42', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '430', 'account_name' => ' الحسم الممنوح', 'master_account_number' =>'43', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '9', 'account_name' => ' الميزانية', 'master_account_number' =>' ', 'report' =>2, 'mainly' =>1,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '91', 'account_name' => ' الأرباح والخسائر', 'master_account_number' =>'9', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        DB::table('tbl_accounts')->insert(['account_number' => '92', 'account_name' => ' المتاجرة', 'master_account_number' =>'9', 'report' =>2, 'mainly' =>0,'user_id'=>0, 'parent_id'=>0 ]);
        
    }
}
